In [0]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
blogText_df = pd.read_csv("/content/gdrive/My Drive/NLP/blogtext.csv")  

In [182]:
blogText_df

id  ...                                               text
0       2059027  ...             Info has been found (+/- 100 pages,...
1       2059027  ...             These are the team members:   Drewe...
2       2059027  ...             In het kader van kernfusie op aarde...
3       2059027  ...                   testing!!!  testing!!!          
4       3581210  ...               Thanks to Yahoo!'s Toolbar I can ...
...         ...  ...                                                ...
681279  1713845  ...         Dear Susan,  I could write some really ...
681280  1713845  ...         Dear Susan,  'I have the second yeast i...
681281  1713845  ...         Dear Susan,  Your 'boyfriend' is fuckin...
681282  1713845  ...         Dear Susan:    Just to clarify, I am as...
681283  1713845  ...         Hey everybody...and Susan,  You might a...

[681284 rows x 7 columns]

In [77]:
blogText_df.shape

(681284, 7)

In [78]:
blogText_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681284 entries, 0 to 681283
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   id      681284 non-null  int64 
 1   gender  681284 non-null  object
 2   age     681284 non-null  int64 
 3   topic   681284 non-null  object
 4   sign    681284 non-null  object
 5   date    681284 non-null  object
 6   text    681284 non-null  object
dtypes: int64(2), object(5)
memory usage: 36.4+ MB


In [79]:
blogText_df.head(10)

id  ...                                               text
0  2059027  ...             Info has been found (+/- 100 pages,...
1  2059027  ...             These are the team members:   Drewe...
2  2059027  ...             In het kader van kernfusie op aarde...
3  2059027  ...                   testing!!!  testing!!!          
4  3581210  ...               Thanks to Yahoo!'s Toolbar I can ...
5  3581210  ...               I had an interesting conversation...
6  3581210  ...               Somehow Coca-Cola has a way of su...
7  3581210  ...               If anything, Korea is a country o...
8  3581210  ...               Take a read of this news article ...
9  3581210  ...               I surf the English news sites a l...

[10 rows x 7 columns]

In [80]:
blogText_df['topic'].unique()

array(['Student', 'InvestmentBanking', 'indUnk', 'Non-Profit', 'Banking',
       'Education', 'Engineering', 'Science', 'Communications-Media',
       'BusinessServices', 'Sports-Recreation', 'Arts', 'Internet',
       'Museums-Libraries', 'Accounting', 'Technology', 'Law',
       'Consulting', 'Automotive', 'Religion', 'Fashion', 'Publishing',
       'Marketing', 'LawEnforcement-Security', 'HumanResources',
       'Telecommunications', 'Military', 'Government', 'Transportation',
       'Architecture', 'Advertising', 'Agriculture', 'Biotech',
       'RealEstate', 'Manufacturing', 'Construction', 'Chemicals',
       'Maritime', 'Tourism', 'Environment'], dtype=object)

In [81]:
blogText_df['sign'].unique()

array(['Leo', 'Aquarius', 'Aries', 'Capricorn', 'Gemini', 'Cancer',
       'Sagittarius', 'Scorpio', 'Libra', 'Virgo', 'Taurus', 'Pisces'],
      dtype=object)

In [82]:
blogText_df['age'].unique()

array([15, 33, 14, 25, 17, 23, 37, 26, 24, 27, 45, 34, 41, 44, 16, 39, 35,
       36, 46, 42, 13, 38, 43, 40, 47, 48])

In [83]:
blogText_df.groupby(blogText_df['age']).count()

id  gender  topic   sign   date   text
age                                           
13   13133   13133  13133  13133  13133  13133
14   27400   27400  27400  27400  27400  27400
15   41767   41767  41767  41767  41767  41767
16   72708   72708  72708  72708  72708  72708
17   80859   80859  80859  80859  80859  80859
23   72889   72889  72889  72889  72889  72889
24   80071   80071  80071  80071  80071  80071
25   67051   67051  67051  67051  67051  67051
26   55312   55312  55312  55312  55312  55312
27   46124   46124  46124  46124  46124  46124
33   17584   17584  17584  17584  17584  17584
34   21347   21347  21347  21347  21347  21347
35   17462   17462  17462  17462  17462  17462
36   14229   14229  14229  14229  14229  14229
37    9317    9317   9317   9317   9317   9317
38    7545    7545   7545   7545   7545   7545
39    5556    5556   5556   5556   5556   5556
40    5016    5016   5016   5016   5016   5016
41    3738    3738   3738   3738   3738   3738
42    2908    2908   2908   2908   2908   2908
43    4230    4230   4230   4230   4230   4230
44    2044    2044   2044   2044   2044   2044
45    4482    4482   4482   4482   4482   4482
46    2733    2733   2733   2733   2733   2733
47    2207    2207   2207   2207   2207   2207
48    3572    3572   3572   3572   3572   3572

In [84]:
blogText_df.groupby(blogText_df['gender']).count()

id     age   topic    sign    date    text
gender                                                
female  336091  336091  336091  336091  336091  336091
male    345193  345193  345193  345193  345193  345193

In [0]:
blogText_df = blogText_df.iloc[0:5000,:]

In [86]:
blogText_df.head(-10)

id  ...                                               text
0     2059027  ...             Info has been found (+/- 100 pages,...
1     2059027  ...             These are the team members:   Drewe...
2     2059027  ...             In het kader van kernfusie op aarde...
3     2059027  ...                   testing!!!  testing!!!          
4     3581210  ...               Thanks to Yahoo!'s Toolbar I can ...
...       ...  ...                                                ...
4985  1103575  ...           yay for uploading my pics on to angel...
4986  1103575  ...         Ok, so this is the last time today, I p...
4987  1103575  ...         oh, and I forgot...  last night at cant...
4988  1103575  ...         So, I got a new commenting host... I di...
4989  1103575  ...         Last night was NOT a good night. {end o...

[4990 rows x 7 columns]

In [0]:
import re, string

def clean_str(string):
  """String cleaning before vectorization
  """
  
  try:    
    string = re.sub(r'^https?:\/\/<>.*[\r\n]*', '', string, flags=re.MULTILINE)
    string  = re.sub(r"[^A-Za-z]", " ", string)         
    words =string.strip().lower().split()    
    words = [w for w in words if len(w)>=1]
    return " ".join(words)	
  except:
    return ""

In [185]:
blogText_df["clean_text"] = blogText_df["text"].apply(clean_str)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [186]:
blogText_df.pop("text")

0                  Info has been found (+/- 100 pages,...
1                  These are the team members:   Drewe...
2                  In het kader van kernfusie op aarde...
3                        testing!!!  testing!!!          
4                    Thanks to Yahoo!'s Toolbar I can ...
                              ...                        
4995           So... I had another one of those dreams...
4996           mmm... strawberry tea for breakfast. To...
4997           Yay for a new layout!!  Yeah, I know, I...
4998           Ok, so I lied... Fed up isn't playing F...
4999           well, today I went to church and talked...
Name: text, Length: 5000, dtype: object

In [187]:
blogText_df.dtypes

id             int64
gender        object
age            int64
topic         object
sign          object
date          object
clean_text    object
dtype: object

In [188]:
blogText_df['age'] = blogText_df['age'].astype(str)
blogText_df['gender'] = blogText_df['gender'].astype(str)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [189]:
blogText_df['labels'] = blogText_df[['gender','age','topic','sign']].agg(','.join,axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [190]:
blogText_df

id  ...                              labels
0     2059027  ...                 male,15,Student,Leo
1     2059027  ...                 male,15,Student,Leo
2     2059027  ...                 male,15,Student,Leo
3     2059027  ...                 male,15,Student,Leo
4     3581210  ...  male,33,InvestmentBanking,Aquarius
...       ...  ...                                 ...
4995  1103575  ...            female,17,indUnk,Scorpio
4996  1103575  ...            female,17,indUnk,Scorpio
4997  1103575  ...            female,17,indUnk,Scorpio
4998  1103575  ...            female,17,indUnk,Scorpio
4999  1103575  ...            female,17,indUnk,Scorpio

[5000 rows x 8 columns]

In [191]:
blogText_df.drop(['id','gender','age','topic','sign','date'],axis=1,inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
from sklearn.model_selection import train_test_split
df_train, df_test, y_train, y_test = train_test_split(blogText_df.clean_text, blogText_df.labels, random_state=30)

In [193]:
#Traing data
print(df_train.shape)
print(df_test.shape)

(3750,)
(1250,)


In [0]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer


In [0]:
cvect = CountVectorizer(stop_words='english',ngram_range=(1,2))

In [196]:
cvect.fit(df_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [199]:
#Check the vocablury size
len(cvect.vocabulary_)

238196

In [0]:
X_train = cvect.transform(df_train)
X_test = cvect.transform(df_test)

In [129]:
X_test.shape

(1250, 238196)

In [130]:
X_train.shape

(3750, 238196)

In [0]:
labelVector = CountVectorizer()
label_ct =labelVector.fit(blogText_df['labels'])
dict_ =label_ct.vocabulary_

In [202]:
dict_

{'14': 0,
 '15': 1,
 '16': 2,
 '17': 3,
 '23': 4,
 '24': 5,
 '25': 6,
 '26': 7,
 '27': 8,
 '33': 9,
 '34': 10,
 '35': 11,
 '36': 12,
 '37': 13,
 '39': 14,
 '41': 15,
 '42': 16,
 '44': 17,
 '45': 18,
 '46': 19,
 'accounting': 20,
 'aquarius': 21,
 'aries': 22,
 'arts': 23,
 'automotive': 24,
 'banking': 25,
 'businessservices': 26,
 'cancer': 27,
 'capricorn': 28,
 'communications': 29,
 'consulting': 30,
 'education': 31,
 'engineering': 32,
 'female': 33,
 'gemini': 34,
 'indunk': 35,
 'internet': 36,
 'investmentbanking': 37,
 'law': 38,
 'leo': 39,
 'libra': 40,
 'libraries': 41,
 'male': 42,
 'media': 43,
 'museums': 44,
 'non': 45,
 'pisces': 46,
 'profit': 47,
 'recreation': 48,
 'religion': 49,
 'sagittarius': 50,
 'science': 51,
 'scorpio': 52,
 'sports': 53,
 'student': 54,
 'taurus': 55,
 'technology': 56,
 'virgo': 57}

In [0]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
Y_train_mlb= mlb.fit_transform(y_train)


In [0]:
Y_test_mlb = mlb.transform(y_test)

In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

In [0]:
clf = LogisticRegression(solver='lbfgs')
clf = OneVsRestClassifier(clf)

In [208]:
clf.fit(X_train,Y_train_mlb)

/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 25 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 29 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 35 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 36 is present in all training examples.
  str(classes[c]))


OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [209]:
from sklearn import metrics
metrics.accuracy_score(Y_test_mlb,clf.predict(X_test))

0.5112

In [210]:
from sklearn.metrics import classification_report
y_predict = clf.predict(X_test)
print(classification_report(Y_test_mlb,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1250
           1       0.82      0.21      0.33        43
           2       0.84      0.47      0.61       230
           3       0.76      0.33      0.46       233
           4       0.86      0.92      0.89       819
           5       0.85      0.53      0.65       268
           6       0.82      0.87      0.84       735
           7       1.00      0.05      0.10        57
           8       0.78      0.22      0.34       116
           9       0.00      0.00      0.00        17
          10       0.84      0.87      0.86       721
          11       1.00      0.35      0.52        40
          12       0.87      0.21      0.33        63
          13       0.53      0.18      0.27        50
          14       0.00      0.00      0.00        22
          15       1.00      0.53      0.69        19
          16       0.69      0.36      0.47       132
          17       0.00    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [211]:
y_test[15]


'male,33,InvestmentBanking,Aquarius'

In [213]:
Y_test_mlb[0]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [214]:
y_predict[0]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [215]:
y_test

2192               male,35,Technology,Aries
911     male,17,Sports-Recreation,Capricorn
3061               male,35,Technology,Aries
3382               male,35,Technology,Aries
2939               male,35,Technology,Aries
                       ...                 
4936               female,17,indUnk,Scorpio
2690               male,35,Technology,Aries
4726               male,25,Technology,Aries
4298           female,34,indUnk,Sagittarius
4412           female,34,indUnk,Sagittarius
Name: labels, Length: 1250, dtype: object

In [0]:
#in the above scenario y_test[2192] is the match

In [224]:
Y_test_mlb[1]

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0])

In [225]:
y_predict[1]

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0])

In [226]:
y_test

2192               male,35,Technology,Aries
911     male,17,Sports-Recreation,Capricorn
3061               male,35,Technology,Aries
3382               male,35,Technology,Aries
2939               male,35,Technology,Aries
                       ...                 
4936               female,17,indUnk,Scorpio
2690               male,35,Technology,Aries
4726               male,25,Technology,Aries
4298           female,34,indUnk,Sagittarius
4412           female,34,indUnk,Sagittarius
Name: labels, Length: 1250, dtype: object

In [0]:
#y_test[911] is a match.

In [233]:
Y_test_mlb[2]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [234]:
y_predict[2]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [0]:
#As it is matching, we will check the actual index in y_test

In [235]:
y_test

2192               male,35,Technology,Aries
911     male,17,Sports-Recreation,Capricorn
3061               male,35,Technology,Aries
3382               male,35,Technology,Aries
2939               male,35,Technology,Aries
                       ...                 
4936               female,17,indUnk,Scorpio
2690               male,35,Technology,Aries
4726               male,25,Technology,Aries
4298           female,34,indUnk,Sagittarius
4412           female,34,indUnk,Sagittarius
Name: labels, Length: 1250, dtype: object

In [0]:
#y_test[3061] is a match

In [236]:
Y_test_mlb[3]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [237]:
y_predict[3]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [0]:
#y_test[3382] is a match

In [238]:
Y_test_mlb[4]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [239]:
y_predict[4]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [0]:
#y_test[2939] is a match

In [231]:
Y_test_mlb[1000]

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0])

In [232]:
y_predict[1000]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0])

In [0]:
#As here y_test_mlb[1000] and y_predict[1000]doesnot match,we will not check the y_test index.

In [0]:
y_pred_ = mlb.inverse_transform(y_predict)

In [167]:
y_pred_[15]

(',', '3', 'a', 'c', 'e', 'g', 'i', 'l', 'm', 'n', 'o', 'r', 's')